config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  resources 'article', only: [:index]
  get "/search", to: "search#index"
  post 'article/search', to: 'article#search'
  root 'article#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/search.rb
class Search < ApplicationRecord
  validates :query, presence: true
  validates :query, length: { minimum: 3, maximum: 50 }
  validates :session_id, presence: true

  def searched?(search)
    jarow = FuzzyStringMatch::JaroWinkler.create(:native)
    similarity_percentage = jarow.getDistance(search, query)
    similarity_percentage > 0.8
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  before_action :check_session, only: [:search]

  def index
    @articles = Article.all.first(50)
  end

  def search
    articles = Article.where('title LIKE ?', "%#{params[:query]}%").first(50)
    render(partial: 'articles', locals: { articles: articles })
    save_search(params[:query], session[:user_id])
  end

  private

  def save_search(query, session)
    return if query.nil? || query.length < 3

    recent_search = Search.new(user_params)
    recent_search.session_id = session
    session_search = Search.where(session_id: session).last
    if session_search.nil? || !session_search.searched?(query)
      recent_search.save
    elsif session_search.query.length < query.length
      session_search.update(query: query)
    end
  end

  def user_params
    params.permit(:query)
  end

  def check_session
    session[:user_id] = SecureRandom.urlsafe_base64(16) if session[:user_id].nil?
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @grouped_searches = Search.group(:query).pluck('query, count(query) as COUNT').sort_by do |a|
      a[1]
    end.reverse.first(100)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/article/_articles.html.erb
<p id="notice"><%= notice %></p>
<h1>Articles</h1>
<div>
  <%= form_with url: article_search_path, method: :post, authenticity_token: false, data: { controller: "search", search_target: "form", turbo_frame: "articles" } do |form| %>
    <%= form.text_field :query,
      placeholder: "Search by title",
      autocomplete: "off",
      data: { action: "input->search#search" }
    %>
  <% end %>
</div>
<%= turbo_frame_tag "articles" do %>
  <% articles.each do |article| %>
    <div class="article">
      <h1><%= article.title %></h1>
      <p><%= article.body %></p>
    </div>
  <% end %>
<% end %>
<!-- Snip the table -->

app/views/article/index.html.erb
<div id="articles-section">
  <%= render partial: 'articles', locals: { articles: @articles } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Searchengine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to 'Articles', root_path %></li>
      <li><%= link_to 'Trending', search_path %></li>
    </ul>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/search/_search.html.erb
<% searches.each do |search, count| %>

<li style="font-size: <%= 25 + count %>px"><%= search %></li>

<% end %>

app/views/search/index.html.erb
<div id="searches">
  <h1> Top 100 Searches </h1>
  <ul id="searches-list">
    <%= render partial: 'search', locals: { searches: @grouped_searches } %>
  </ul>
</div>